# Site settings
title: React Patterns
email: mijoch+learnreact@domain.com
description: > # this means to ignore newlines until "baseurl:"
  React Patterns is a collection of practices and patterns out in the wild.
  This collection is a simple observation of patterns and doesn't perscribe to
  to one way being better than another. In fact many of these patterns may not be reasonable used together.
  This is simply a glossery of terms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reactpatterns.com" # the base hostname & protocol for your site
twitter_username: learnreact
github_username:  learnreact

permalink: :title

# Build settings
markdown: kramdown
highlighter: pygments
